# Generated by Django 4.1.8 on 2023-04-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SEGUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('US_UsuarioId', models.IntegerField(db_column='US_UsuarioId')),
                ('US_Login', models.CharField(db_column='US_Loging', max_length=100)),
                ('US_Password', models.CharField(db_column='US_Password', max_length=100)),
            ],
            options={
                'db_table': 'SEGUsuario',
            },
        ),
    ]
